server:
    port: 8881
spring:
  application:
    name: banking
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: Eton@2024
    url: jdbc:sqlserver://localhost:1433;databaseName=banking;encrypt=true;trustServerCertificate=true
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
      show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
